### ISSUE TITLE
build constraints exclude all Go files in...

### ISSUE THREAD

**Issue by flibustenet** [benbjohnson/genesis#2]
I generate a file of assets to build from linux for windows 386.
If i omit  `-tags "386"` it give me this error `build constraints exclude all Go files in...` 
With the tags it works.

Is this tags not optional ?

**Comment by benbjohnson** [comment]
It was a dumb bug on my part. @janos fixed it in https://github.com/benbjohnson/genesis/pull/1. The latest release (`v0.1.3`) has the fix included.
