### ISSUE TITLE
Switch to SHA256

### ISSUE THREAD

**Issue by lukechampine** [benbjohnson/genesis#4]
Collisions have been demonstrated for SHA1: https://shattered.io

Is this a problem? Depends on what you're using `genesis` for. Generating the collisions requires that the attacker control both preimages, which isn't likely to be the case for assets embedded in a binary. But why take chances?

The only blocker I could see here is compatibility. If you aren't willing to break compatibility, perhaps at least a warning in the README about SHA1 would suffice.

**Comment by benbjohnson** [comment]
Yeah, it's unlikely to be an attack vector but you're right—why take chances. Fixed via #5.

**Comment by benbjohnson** [comment]
Tagged `v0.2.0` with the hash encoding & SHA1 changes. Thanks @lukechampine!
